### ISSUE TITLE
Doesn't work in safari

### ISSUE THREAD

**Issue by klausdk** [footniko/mediasoup-sample#1]
This sample helped me alot! Thanks!

However, it didn't work out of the box on safari on iphone.

I fixed it by adding 

`video.setAttribute('playsinline', '');`

in the "handleConsumer" function in the app.js file.

I also used the "H264" config in config.js instead of VP8

/Klaus

**Comment by footniko** [comment]
Yes, you're right. iOS has its own restrictions on auto-playing media.
Thanks!
