### ISSUE TITLE
TypeError: navigator.mediaDevices

### ISSUE THREAD

**Issue by alexnavarrova** [footniko/mediasoup-sample#10]
Buen dia gracias por compartir y contribuir con los que estamos empezando

se me ha presentado un error al lanzarlo en el navegador, sale este error

TypeError: navigator.mediaDevices is undefined

Gracias

**Comment by footniko** [comment]
@alexnavarrova please, follow the installation guide. You probably haven't installed frontend npm packages.
Also, please use English, I don't speak Spanish :(

**Comment by alexnavarrova** [comment]
ok, thanks for your answerd.
I follow the installation guide and i installed the npm packages

cd frontend
npm install

> added 50 packages from 37 contributors and audited 126 packages in 5.14s

npm start

**Comment by footniko** [comment]
The problem occurs because you do not use SSL, nor localhost URL, closing.
