### ISSUE TITLE
not working on production env 

### ISSUE THREAD

**Issue by rohityadav1** [footniko/mediasoup-sample#2]
Hi,
This code is working fine on local machine (development environment ), but it is not working on production environment (https://mediasoup.galaxysofttech.co.in/). I have debug in Chrome ( Version 69.0.3497.100 (Official Build) (64-bit) - os: ubuntu 16.04) webrtc-internals. i found that its iceconnectionstatechange was failed. Please help me to sort out this issue.
I am attaching dumps of webrtc-internals.
[webrtc_internals_dump.txt](https://github.com/footniko/mediasoup-sample/files/2594083/webrtc_internals_dump.txt)

**Comment by footniko** [comment]
Hi. First of all, make sure you have opened ports on your prod server (from 40000 to 49999, as per `server/config.js` **rtcMinPort** and **rtcMaxPort** variables). Secondly, if you use AWS, you need to set **rtcAnnouncedIPv4** in the config to the public ip of your instance (note, it may be required for other servers as well). And lastly, there is a very little probability, that you need to use turn servers to make it working (see https://mediasoup.org/documentation/mediasoup-client/api/#Room-RoomOptions)

**Comment by rohityadav1** [comment]
Super
I have opened ports from 40000 to 49999. That works for me.
Very Very Thanks.
