### ISSUE TITLE
delay in live stream

### ISSUE THREAD

**Issue by rohityadav1** [footniko/mediasoup-sample#3]
Hi,
I am able to do conference call using your code. But problem is this, it is showing ~10 seconds of  delay in audio and showing ~40 seconds of delay in video. This is not acceptable in any case.
Details as given below
Connected User: 2
Downloading speed of client machine ~20Mbps and uploading speed  is ~40Mbps.
I am using AWS server (8GB of Ram and quad core processor), having bandwidth of up to 10GB.
URL: https://mediasoup.galaxysofttech.co.in/?roomId=room1.

Please help me to sort out this issue.

**Comment by footniko** [comment]
Hi,
It looks like network issues. Usually, the delay is less, than 0.5 sec. if the network bandwidth is enough and connection is stable (without packets loss). If you want, you may try other media servers, but I don't think it's related to MediaSoup.

**Comment by rohityadav1** [comment]
Hi,
Thanks for replying. But I have solved it by myself by modifying index.js file (newtransport section) i.e.
mediaPeer.on('newtransport', (transport) => {
        console.log('New mediaPeer transport:', transport.direction);
         if (transport.direction === 'send') {
            transport.setMaxBitrate(config.mediasoup.maxBitrate);
         }
        transport.on('close', (originator) => {
          console.log('Transport closed from originator:', originator);
        });
      });
then I have set lower value of config.mediasoup.maxBitrate in config. I resolved it

**Comment by footniko** [comment]
Glad to hear you've solved it. Thanks for posting the solution!
