### ISSUE TITLE
call recording feature

### ISSUE THREAD

**Issue by rohityadav1** [footniko/mediasoup-sample#4]
Hi,
Could this code support server side call recording? If yes, can you share a sample code with us?

**Comment by footniko** [comment]
This is just a sample code of the official [MediaSoup](https://github.com/versatica/mediasoup/) package, that aims to make it easier to adopt the [MediaSoup](https://github.com/versatica/mediasoup/). It covers just basic things that related to streaming. You need to refer to the [official MediaSoup project](https://mediasoup.org/) for any other stuff.
AFAIK, there is no official support for recording. But MediaSoup allows you to access raw RTP packets, which you can handle as you want.
Here are some references:
[https://groups.google.com/forum/#!topic/mediasoup/3FOeMbM8SHQ](https://groups.google.com/forum/#!topic/mediasoup/3FOeMbM8SHQ)
