### ISSUE TITLE
issue of primus socket

### ISSUE THREAD

**Issue by nodejscss** [footniko/mediasoup-sample#7]
Hi, FootNiko,

When I test the sample, have a problem that is:
I replace socket.io.js with primus.js and primus-emit, because the socket.io often broken on cordova mobile application. However the sample can not join room but say 'timeout'.

How can I fix the problem? Does the mediasoup not fit to the primus.js ?

Thank you very much.

**Comment by footniko** [comment]
Hi,
You can use MediaSoup with any signaling library you prefer.
If it doesn't work, probably you're doing something wrong. Make sure you understand the workflow and just replicate it with primus.js (I haven't used primus, so not sure I'll be much helpful).

**Comment by nodejscss** [comment]
Hi, footniko,

I found the error when using primus.
AT CLIENT LOG:

at server log:
request: { method: 'queryRoom', target: 'room' }
incoming::data :  {"emit":["mediasoup-request",{"method":"queryRoom","target":"room"},null]}
queryRoom response: { rtpCapabilities:
   { codecs: [ [Object], [Object], [Object] ],
     headerExtensions:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     fecMechanisms: [] },
  mandatoryCodecPayloadTypes: [] }
queryRoom error: TypeError: cb is not a function

**Comment by nodejscss** [comment]
Hi, footniko,

I found the error when using primus, that is the cb of "spark.on('mediasoup-request', (request, cb)" is NOT a function.

AT CLIENT, the statement, primus.emit('mediasoup-request', request, (err, response) => {});
LOG: 
outgoing::data :  {"emit":["mediasoup-request",{"method":"queryRoom","target":"room"},null]}

AT SERVER, the statement, room.receiveRequest(request)
        .then((response) => {console.log('queryRoom response:', response);cb(null, response)})
LOG:
request: { method: 'queryRoom', target: 'room' }
incoming::data : {"emit":["mediasoup-request",{"method":"queryRoom","target":"room"},null]}
queryRoom response: { rtpCapabilities:
{ codecs: [ [Object], [Object], [Object] ],
headerExtensions:
[ [Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object] ],
fecMechanisms: [] },
mandatoryCodecPayloadTypes: [] }
queryRoom error: TypeError: cb is not a function

cb is NOT a function. How to set the cb to a function?

Thank you very much.

**Comment by footniko** [comment]
Please, try to ask such a kind of questions on StackOverflow since they are programming related questions and have nothing to do with MediaSoup.
