### ISSUE TITLE
Server npm i error. (win 10)

### ISSUE THREAD

**Issue by DimitrisTzimikas** [footniko/mediasoup-sample#9]
@footniko first of all thanks for the repo. 

I'm on windows 10-64bit, node: 10.9.0, npm:6.5.0. 
On server folder when I try **npm i** I get this error: 

``
npm ERR! code EBADPLATFORM 

npm ERR! notsup Unsupported platform for mediasoup@2.6.12: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
``

Question: The installation is suppose to run only on mac and not windows or I'm doing something wrong?

Thanks in advance.

**Comment by footniko** [comment]
@DimitrisTzimikas, as you can see from the message, MediaSoup is not supported on your platform. It's mentioned in the docs of the MediaSoup:
>POSIX based operating system (Windows not supported)

**Comment by DimitrisTzimikas** [comment]
@footniko thanks for the answer! Sorry didn't see that in docs tho.
